import streamlit as st
import google.generativeai as genai
from PIL import Image
import fitz  # PyMuPDF
import time
import json
import io

# ==========================================
# 1. CORE BRAIN: INITIALIZE AI
# ==========================================
@st.cache_resource
def load_axom_engine():
    try:
        if "GEMINI_KEY" not in st.secrets:
            return None, "Missing API Key in Streamlit Secrets."
        genai.configure(api_key=st.secrets["GEMINI_KEY"])
        # Using Gemini 2.0 Flash for superior vision/graph analysis
        model = genai.GenerativeModel('gemini-2.0-flash')
        return model, None
    except Exception as e:
        return None, str(e)

model, error_message = load_axom_engine()

if "history" not in st.session_state:
    st.session_state.history = []

# ==========================================
# 2. THE HANDS: RED PEN PAINTER
# ==========================================
def apply_harsh_marking(uploaded_file, ai_json_instructions):
    try:
        input_bytes = uploaded_file.getvalue()
        doc = fitz.open(stream=input_bytes, filetype="pdf")
        for action in ai_json_instructions:
            for page in doc:
                text_instances = page.search_for(action["text"])
                for inst in text_instances:
                    if action["action"] == "strike_through":
                        # Draw red line through text
                        line_mid = (inst.y0 + inst.y1) / 2
                        annot = page.add_line_annot(fitz.Point(inst.x0, line_mid), fitz.Point(inst.x1, line_mid))
                        annot.set_colors(stroke=(1, 0, 0)) # Red color
                        annot.update()
                        
                        # Add comment box
                        page.add_text_annot(fitz.Point(inst.x1 + 5, inst.y0), action["comment"])
        return doc.write()
    except:
        return None

# ==========================================
# 3. USER INTERFACE (UI)
# ==========================================
st.set_page_config(page_title="AXOM Global", layout="wide")

# Custom Branding Header
st.markdown(
    """
    <div style='background-color: #001F3F; padding: 20px; border-radius: 10px; border-bottom: 5px solid #D4AF37;'>
        <h1 style='color: white; text-align: center; margin: 0;'>AXOM GLOBAL</h1>
        <p style='color: #D4AF37; text-align: center; font-weight: bold;'>SENIOR EXAMINER AI SYSTEM</p>
    </div>
    <br>
    """,
    unsafe_allow_html=True
)

with st.sidebar:
    st.header("Submission History")
    if not st.session_state.history:
        st.write("No papers marked yet.")
    else:
        for item in reversed(st.session_state.history):
            st.write(f"**{item['filename']}**")
            st.caption(f"Mode: {item['mode']} | {item['timestamp']}")
            st.divider()
        
        if st.button("Clear History"):
            st.session_state.history = []
            st.rerun()

if error_message:
    st.error(f"Engine Offline: {error_message}")
    st.stop()

uploaded_file = st.file_uploader("Upload Exam Paper (PDF)", type=['pdf'])

if uploaded_file:
    rigor = st.select_slider("Select Marking Rigor", options=["Standard", "Harsh"])
    
    with st.expander("View Full Terms of Service"):
        st.markdown("""
        **1. Nature of Service:** AXOM provides automated, AI-generated feedback based on 2026 academic descriptors.
        **2. Accuracy:** Results are generated by the AXOM Neural Engine and are not official certifications.
        **3. Data Privacy:** PDF files are processed in real-time and not stored permanently.
        **4. Agreement:** You agree to the 30-second analysis gate for senior-level evaluation.
        """)
    
    tos_agreed = st.checkbox("I have read and agree to the Terms of Service")
    run_button = st.button("RUN AXOM ANALYSIS", disabled=not tos_agreed)
    
    if run_button:
        timer_placeholder = st.empty()
        progress_bar = st.progress(0)
        
        status_updates = [
            "Initializing AXOM Neural Engine...",
            "Fetching Mark Scheme for Accuracy...",
            "Scanning syntax and morphology...",
            "Comparing vocabulary to High-class descriptors...",
            "Analyzing graphs and visual data...",
            "Generating Senior Lecturer feedback..."
        ]

        for i in range(30):
            msg = status_updates[i // 5]
            with timer_placeholder.container():
                st.markdown(f"### {msg}")
                st.info(f"Analysis in progress: {30 - i}s remaining.")
                st.caption("ADVERTISEMENT: Prepare for your EXAMS with AXOM Premium. No wait times. 100% Accuracy.")
            progress_bar.progress((i + 1) / 30)
            time.sleep(1)
        
        timer_placeholder.empty()
        progress_bar.empty()

        with st.spinner("Finalizing report..."):
            try:
                pdf_parts = [{"mime_type": "application/pdf", "data": uploaded_file.getvalue()}]
                
                prompt = (
                    f"You are a Senior Lecturer. Mark this paper in {rigor} mode. "
                    "Special Instruction: If the student has described a graph or chart, "
                    "carefully verify their data against the visual image provided. "
                    "Check for accuracy in trends, percentages, and comparisons. "
                    "Provide a Band score based on 'Task Response' and 'Cohesion'. "
                    "Format: JSON_START "
                    "[{\"action\": \"strike_through\", \"text\": \"word\", \"comment\": \"explanation\"}] "
                    "JSON_END"
                )
                
                response = model.generate_content([prompt] + pdf_parts)
                full_text = response.text
                
                correction_list = []
                report_text = full_text

                if "JSON_START" in full_text and "JSON_END" in full_text:
                    try:
                        report_text = full_text.split("JSON_START")[0]
                        json_part = full_text.split("JSON_START")[1].split("JSON_END")[0]
                        correction_list = json.loads(json_part.strip())
                    except:
                        correction_list = []

                st.session_state.history.append({
                    "filename": uploaded_file.name,
                    "mode": rigor,
                    "timestamp": time.strftime("%H:%M:%S"),
                    "report": report_text
                })

                st.markdown("---")
                st.markdown("### Examiner Report")
                st.write(report_text)
                
                marked_pdf = apply_harsh_marking(uploaded_file, correction_list)
                
                if marked_pdf:
                    st.download_button(
                        label="Download Annotated PDF", 
                        data=marked_pdf, 
                        file_name=f"AXOM_Marked_{uploaded_file.name}",
                        mime="application/pdf"
                    )
                    
            except Exception as e:
                st.error(f"Analysis failed: {e}")

# ==========================================
# 4. FOOTER
# ==========================================
st.markdown("---")
footer_col1, footer_col2, footer_col3 = st.columns([1, 2, 1])

with footer_col2:
    st.markdown(
        """
        <div style='text-align: center; color: grey;'>
            <p>© 2026 AXOM Global | Senior Examiner AI v2.0</p>
            <p style='font-size: 0.8rem;'>Built for IGCSE/O-LEVELS/A-LEVELS/IELTS Standards</p>
        </div>
        """,
        unsafe_allow_html=True
    )
